### ISSUE TITLE
Intro to functions lab

### ISSUE THREAD

**Issue by Retroviridae** [learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab#16]
### Canvas Link

https://learning.flatironschool.com/courses/5470/assignments/168079?module_item_id=363183

### Concern

I keep failing the first test with the error "  Error: spy was never called with [ 'HELLO' ]". Spy is not addressed in the lesson and I cannot figure out what it wants me to do from the index.test file.

**Comment by lizbur10** [comment]
Hi @Retroviridae! The spy is how the test determines whether a value has been logged using console.log(). If you're seeing that error, that tells you that the test requires you to console.log a value in your function. 

If you still need help with this, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.
