### ISSUE TITLE
i need to summit the assigment again

### ISSUE THREAD

**Issue by melissa0191** [learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab#36]
### Canvas Link

https://learning.flatironschool.com/courses/7164/assignments/252921?module_item_id=597732

### Concern

I summited an assigment and it was incorrect, i need to summit it again but its not lettimg me

**Comment by lizbur10** [comment]
Hi @melissa0191 ! If you submitted using CodeGrade, it should update automatically when you push your new changes to GitHub. If you're still having problems with this, you should use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team. 

Good luck! 💙
