### ISSUE TITLE
Change sayHiToGrandma() to sayHiToHeadphonedRoomate(), and "I love you, Grandma." to "Let's have dinner, together!"

### ISSUE THREAD

**Issue by rebekah-zhou** [learn-co-curriculum/phase-0-pac-3-intro-to-functions-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/5055/assignments/152503

### Concern

The readme asks for function sayHiToGrandma() but the index-test.js asks for sayHiToHeadphonedRoomate(), which is also spelled wrong (roommate). In addition, the readme states: If the string that is passed into the function is equal to "I love you, Grandma.", the function should return "I would love to!", but the index-test.js expects "Let's have dinner, together!" instead of "I love you, Grandma." as stated on lines 47-49.

**Comment by ihollander** [comment]
Hi @rebekah-zhou - thanks for bringing this to our attention! We will update the readme and tests to make sure the instructions are consistent.
